
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_document_groups` DISABLE KEYS */;
REPLACE INTO `modx_document_groups` VALUES (8,2,12);
REPLACE INTO `modx_document_groups` VALUES (16,2,11);
REPLACE INTO `modx_document_groups` VALUES (10,3,1);
REPLACE INTO `modx_document_groups` VALUES (23,3,17);
REPLACE INTO `modx_document_groups` VALUES (22,3,16);
REPLACE INTO `modx_document_groups` VALUES (13,3,13);
REPLACE INTO `modx_document_groups` VALUES (25,3,26);
REPLACE INTO `modx_document_groups` VALUES (26,3,27);
REPLACE INTO `modx_document_groups` VALUES (27,3,28);
REPLACE INTO `modx_document_groups` VALUES (28,3,35);
REPLACE INTO `modx_document_groups` VALUES (19,3,7);
REPLACE INTO `modx_document_groups` VALUES (20,3,8);
REPLACE INTO `modx_document_groups` VALUES (24,3,25);
REPLACE INTO `modx_document_groups` VALUES (29,3,36);
/*!40000 ALTER TABLE `modx_document_groups` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

