
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_categories` DISABLE KEYS */;
REPLACE INTO `modx_categories` VALUES (1,0,'FormIt',0);
REPLACE INTO `modx_categories` VALUES (3,0,'BreadCrumb',0);
REPLACE INTO `modx_categories` VALUES (5,0,'pdoTools',0);
REPLACE INTO `modx_categories` VALUES (8,0,'AjaxForm',0);
REPLACE INTO `modx_categories` VALUES (17,0,'ClientConfig',0);
REPLACE INTO `modx_categories` VALUES (18,0,'miniShop2',0);
REPLACE INTO `modx_categories` VALUES (19,0,'controlErrorLog',0);
REPLACE INTO `modx_categories` VALUES (20,0,'Collections',0);
REPLACE INTO `modx_categories` VALUES (21,0,'ms2Gallery',0);
REPLACE INTO `modx_categories` VALUES (22,0,'Text Page',0);
REPLACE INTO `modx_categories` VALUES (23,0,'MIGX',0);
REPLACE INTO `modx_categories` VALUES (24,0,'Файлы',0);
REPLACE INTO `modx_categories` VALUES (25,0,'О продукции',0);
REPLACE INTO `modx_categories` VALUES (26,0,'Блок с электрикой',0);
REPLACE INTO `modx_categories` VALUES (27,0,'Блок с регистрацией',0);
REPLACE INTO `modx_categories` VALUES (28,0,'Рабочий процесс видео',0);
/*!40000 ALTER TABLE `modx_categories` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

