
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_access_resource_groups` DISABLE KEYS */;
REPLACE INTO `modx_access_resource_groups` VALUES (9,'2','modUserGroup',4,9999,4,'web');
REPLACE INTO `modx_access_resource_groups` VALUES (3,'2','modUserGroup',1,9999,1,'mgr');
REPLACE INTO `modx_access_resource_groups` VALUES (4,'3','modUserGroup',1,9999,1,'web');
REPLACE INTO `modx_access_resource_groups` VALUES (5,'3','modUserGroup',1,9999,1,'mgr');
REPLACE INTO `modx_access_resource_groups` VALUES (6,'3','modUserGroup',0,9999,4,'web');
REPLACE INTO `modx_access_resource_groups` VALUES (7,'3','modUserGroup',0,9999,4,'mgr');
/*!40000 ALTER TABLE `modx_access_resource_groups` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

