
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_categories_closure` DISABLE KEYS */;
REPLACE INTO `modx_categories_closure` VALUES (1,1,0);
REPLACE INTO `modx_categories_closure` VALUES (0,1,0);
REPLACE INTO `modx_categories_closure` VALUES (3,3,0);
REPLACE INTO `modx_categories_closure` VALUES (0,3,0);
REPLACE INTO `modx_categories_closure` VALUES (5,5,0);
REPLACE INTO `modx_categories_closure` VALUES (0,5,0);
REPLACE INTO `modx_categories_closure` VALUES (0,8,0);
REPLACE INTO `modx_categories_closure` VALUES (8,8,0);
REPLACE INTO `modx_categories_closure` VALUES (17,17,0);
REPLACE INTO `modx_categories_closure` VALUES (0,17,0);
REPLACE INTO `modx_categories_closure` VALUES (18,18,0);
REPLACE INTO `modx_categories_closure` VALUES (0,18,0);
REPLACE INTO `modx_categories_closure` VALUES (19,19,0);
REPLACE INTO `modx_categories_closure` VALUES (0,19,0);
REPLACE INTO `modx_categories_closure` VALUES (20,20,0);
REPLACE INTO `modx_categories_closure` VALUES (0,20,0);
REPLACE INTO `modx_categories_closure` VALUES (21,21,0);
REPLACE INTO `modx_categories_closure` VALUES (0,21,0);
REPLACE INTO `modx_categories_closure` VALUES (22,22,0);
REPLACE INTO `modx_categories_closure` VALUES (0,22,0);
REPLACE INTO `modx_categories_closure` VALUES (23,23,0);
REPLACE INTO `modx_categories_closure` VALUES (0,23,0);
REPLACE INTO `modx_categories_closure` VALUES (24,24,0);
REPLACE INTO `modx_categories_closure` VALUES (0,24,0);
REPLACE INTO `modx_categories_closure` VALUES (25,25,0);
REPLACE INTO `modx_categories_closure` VALUES (0,25,0);
REPLACE INTO `modx_categories_closure` VALUES (26,26,0);
REPLACE INTO `modx_categories_closure` VALUES (0,26,0);
REPLACE INTO `modx_categories_closure` VALUES (27,27,0);
REPLACE INTO `modx_categories_closure` VALUES (0,27,0);
REPLACE INTO `modx_categories_closure` VALUES (28,28,0);
REPLACE INTO `modx_categories_closure` VALUES (0,28,0);
REPLACE INTO `modx_categories_closure` VALUES (29,29,0);
REPLACE INTO `modx_categories_closure` VALUES (0,29,0);
REPLACE INTO `modx_categories_closure` VALUES (30,30,0);
REPLACE INTO `modx_categories_closure` VALUES (0,30,0);
REPLACE INTO `modx_categories_closure` VALUES (31,31,0);
REPLACE INTO `modx_categories_closure` VALUES (0,31,0);
REPLACE INTO `modx_categories_closure` VALUES (32,32,0);
REPLACE INTO `modx_categories_closure` VALUES (0,32,0);
/*!40000 ALTER TABLE `modx_categories_closure` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

