
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_ms2_options` DISABLE KEYS */;
REPLACE INTO `modx_ms2_options` VALUES (1,'proizvoditel','Производитель',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (2,'nominalnyy_tok_In','Номинальный ток In',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (3,'kolichestvo_polyusov','Количество полюсов',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (4,'harakteristika_otklyucheniya','Характеристика отключения',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (5,'predelnaya_kommutatsionnaya_sposobnost_Icn','Предельная коммутационная способность Icn',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (6,'nominalnoe_napryazhenie_as_Un','Номинальное напряжение АС Un',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (7,'chastota','Частота',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (8,'nominalnoe_napryazhenie_izolyatsii_Ui','Номинальное напряжение изоляции Ui',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (9,'impulsnoe_vyderzhivaemoe_napryazhenie','Импульсное выдерживаемое напряжение',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (10,'stepen_zaschity','Степень защиты',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (11,'rabochaya_temperatura','Рабочая температура',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (12,'seriya','Серия',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (13,'nominalnyy_otklyuchayuschiy_differentsialnyy_tok_l∆n','Номинальный отключающий дифференциальный ток l∆n',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (14,'nominalnyy_neotklyuchayuschiy_differentsialnyy_tok','Номинальный неотключающий дифференциальный ток',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (15,'tip_uzo','Тип УЗО',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (16,'ves','Вес',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (17,'nominalnyy_otklyuchayuschiy_differentsialnyy_tok_I∆n','Номинальный отключающий дифференциальный ток I∆n',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (18,'predelnaya_kommutatsionnaya_sposobnost_Icu','Предельная коммутационная способность Icu',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (19,'temperatura_kalibrovki','Температура калибровки',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (20,'material','Материал',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (21,'dlina','Длина','','М',32,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (22,'profil','Профиль',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (23,'tip_podklyucheniya','Тип подключения',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (24,'sechenie_provodnika','Сечение проводника',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (25,'kolichestvo_gnezd','Количество гнезд',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (26,'upakovka','Упаковка',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (27,'tsvet_vstavki','Цвет вставки',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (28,'tsvet','Цвет',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (29,'kontaktnaya_chast','Контактная часть',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (30,'material_korpusa','Материал корпуса',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (31,'diametr_kabelya','Диаметр кабеля',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (32,'tip_rezby','Тип резьбы',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (33,'klass_tochnosti','Класс точности',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (34,'razmer_litsevoy_paneli','Размер лицевой панели',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (35,'massa','Масса',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (36,'sposob_vklyucheniya','Способ включения',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (37,'diapazon_izmereniy','Диапазон измерений',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (38,'nominalnoe_rabochee_napryazhenie_Ue','Номинальное рабочее напряжение Ue',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (39,'nominalnaya_chastota','Номинальная частота','','А',32,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (40,'nominalnoe_napryazhenie_transformatora_Unom','Номинальное напряжение трансформатора Uном.',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (41,'naibolshee_rabochee_napryazhenie','Наибольшее рабочее напряжение',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (42,'nominalnaya_chastota_napryazheniya_seti_fnom','Номинальная частота напряжения сети fном',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (43,'nominalnyy_pervichnyy_tok_transformatora_Inom','Номинальный первичный ток трансформатора Iном',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (44,'nominalnyy_vtorichnyy_tok__Inom','Номинальный вторичный ток  Iном',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (45,'nominalnaya_vtorichnaya_nagruzka_Snom_s_koeffitsientom_moschnosti_cosf208','Номинальная вторичная нагрузка Sном с коэффициентом мощности cosφ2=0,8',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (46,'vstroennaya_shirina','Встроенная ширина',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (47,'kolichestvo_shin','Количество шин',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (48,'razmer_shiny_shhv','Размер шины ШхВ',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (49,'napryazhenie_pitaniya','Напряжение питания',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (50,'kolichestvo_faz','Количество фаз','','',32,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (51,'potreblyaemaya_moschnost','Потребляемая мощность','','В',32,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (52,'diapazon_regulirovki_Ir','Диапазон регулировки Ir',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (53,'diapazon_rabochih_tokov_sovmestimyh_kontaktorov_a','Диапазон рабочих токов совместимых контакторов, А',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (54,'tiporazmer_sovmestimyh_kontaktorov','Типоразмер совместимых контакторов',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (55,'sovmestimye_modeli_kontaktorov','Совместимые модели контакторов',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (56,'montazh','Монтаж',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (57,'kolichestvo_moduley','Количество модулей',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (58,'iznosostoykost_mehanicheskaya/elektricheskaya','Износостойкость механическая/электрическая',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (59,'maksimalnyy_kommutiruemyy_tok_As-1','Максимальный коммутируемый ток AС-1',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (60,'regulirovka__poroga_srabatyvaniya','Регулировка  порога срабатывания',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (61,'kontakty','Контакты',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (62,'diapazon_regulirovki_poroga_srabatyvaniya','Диапазон регулировки порога срабатывания',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (63,'napryazhenie_pitaniya_Up','Напряжение питания Uп',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (64,'tip_funktsii','Тип Функции',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (65,'tip_knopki','Тип кнопки',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (66,'tsvet_tolkatelya','Цвет толкателя',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (67,'mehanicheskaya_iznosostoykost_tsiklov_Bo','Механическая износостойкость, циклов BО',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (68,'tip_kontaktov','Тип контактов',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (69,'nominalnyy_teplovoy_tok_Ith','Номинальный тепловой ток Ith',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (70,'kategoriya_primeneniya','Категория применения',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (71,'tip_signala','Тип сигнала',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (72,'rabochee_napryazhenie_AC_Ue','Рабочее напряжение AC Ue',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (73,'rabochaya_kommutatsionnaya_sposobnost_lcs','Рабочая коммутационная способность lcs',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (74,'nominalnyy_kratkovremennyy_vyderzhivaemyy_tok_lcw','Номинальный кратковременный выдерживаемый ток lcw',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (75,'otnoshenie_nlcm/lcu','Отношение n=lcm/lcu',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (76,'klass_otklyuchayuschey_sposobnosti','Класс отключающей способности',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (77,'nalichie_elektroprivoda','Наличие электропривода',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (78,'tip_rastsepitelya','Тип расцепителя',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (79,'protokol_peredachi_dannyh','Протокол передачи данных',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (80,'uslovnyy_teplovoy_tok_na_otkrytom_vozduhe_a','Условный тепловой ток на открытом воздухе, А',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (81,'vysota_nad_urovnem_morya_m','Высота над уровнем моря, м',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (82,'tip_rukoyatki','Тип рукоятки',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (83,'uslovnyy_teplovoy_tok','Условный тепловой ток',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (84,'gabarit_plavkoy_vstavki','Габарит плавкой вставки',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (85,'polozhenie_rukoyatki','Положение рукоятки',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (86,'kolichestvo_napravleniy','Количество направлений',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (87,'reaktivnaya_moschnost_Qn','Реактивная мощность Qn',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (88,'nominalnaya_yomkost_Cn','Номинальная ёмкость Cn',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (89,'gabarity_korpusa','Габариты корпуса',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (90,'otklonenie_yomkosti','Отклонение ёмкости',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (91,'soedinenie','Соединение',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (92,'puskovoy_tok_Is','Пусковой ток Is',NULL,NULL,0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (93,'maksimalno_dopustimyy_tok','Максимально допустимый ток',NULL,'',0,'textfield',NULL);
REPLACE INTO `modx_ms2_options` VALUES (94,'vremya_razmykaniya','Время размыкания',NULL,'',0,'textfield',NULL);
/*!40000 ALTER TABLE `modx_ms2_options` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

