
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_site_tmplvar_templates` DISABLE KEYS */;
REPLACE INTO `modx_site_tmplvar_templates` VALUES (1,3,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (2,3,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (3,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (4,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (5,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (6,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (7,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (8,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (9,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (10,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (11,35,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (3,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (4,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (8,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (9,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (10,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (11,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (12,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (13,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (14,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (15,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (16,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (17,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (18,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (3,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (4,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (8,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (9,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (17,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (18,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (19,34,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (12,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (19,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (20,28,0);
REPLACE INTO `modx_site_tmplvar_templates` VALUES (21,28,0);
/*!40000 ALTER TABLE `modx_site_tmplvar_templates` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

