
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

/*!40000 ALTER TABLE `modx_site_plugin_events` DISABLE KEYS */;
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnWebPagePrerender',-100,0);
REPLACE INTO `modx_site_plugin_events` VALUES (2,'OnRichTextBrowserInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (2,'OnRichTextEditorRegister',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (2,'OnRichTextEditorInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnFileEditFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnTempFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnChunkFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnPluginFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnSnipFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (13,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnMODXInit',-100,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnSiteRefresh',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (9,'OnBeforeSaveWebPageCache',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (16,'OnMODXInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (16,'OnHandleRequest',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (16,'pdoToolsOnFenomInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnMODXInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnHandleRequest',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnLoadWebDocument',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnWebPageInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'OnUserSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (17,'msOnChangeOrderStatus',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (18,'OnBeforeRegisterClientScripts',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnManagerPageInit',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnBeforeDocFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnResourceBeforeSort',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnDocFormPrerender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnBeforeEmptyTrash',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnDocFormRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnManagerPageBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'FredOnBeforeGetResourceTree',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'FredBeforeRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (19,'OnResourceDuplicate',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (20,'OnDocFormRender',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (20,'OnLoadWebDocument',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (20,'OnBeforeDocFormSave',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (20,'OnBeforeEmptyTrash',0,0);
REPLACE INTO `modx_site_plugin_events` VALUES (21,'OnRichTextEditorRegister',0,0);
/*!40000 ALTER TABLE `modx_site_plugin_events` ENABLE KEYS */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

